<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cargo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cargo_model');
    } 

    /*
     * Listing of cargo
     */
    function index()
    {
        $data['cargo'] = $this->Cargo_model->get_all_cargo();
        
        $data['_view'] = 'cargo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cargo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombreCargo' => $this->input->post('nombreCargo'),
				'sueldoCargo' => $this->input->post('sueldoCargo'),
            );
            
            $cargo_id = $this->Cargo_model->add_cargo($params);
            redirect('cargo/index');
        }
        else
        {            
            $data['_view'] = 'cargo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cargo
     */
    function edit($idCargo)
    {   
        // check if the cargo exists before trying to edit it
        $data['cargo'] = $this->Cargo_model->get_cargo($idCargo);
        
        if(isset($data['cargo']['idCargo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombreCargo' => $this->input->post('nombreCargo'),
					'sueldoCargo' => $this->input->post('sueldoCargo'),
                );

                $this->Cargo_model->update_cargo($idCargo,$params);            
                redirect('cargo/index');
            }
            else
            {
                $data['_view'] = 'cargo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cargo you are trying to edit does not exist.');
    } 

    /*
     * Deleting cargo
     */
    function remove($idCargo)
    {
        $cargo = $this->Cargo_model->get_cargo($idCargo);

        // check if the cargo exists before trying to delete it
        if(isset($cargo['idCargo']))
        {
            $this->Cargo_model->delete_cargo($idCargo);
            redirect('cargo/index');
        }
        else
            show_error('The cargo you are trying to delete does not exist.');
    }
    
}
