<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empleado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empleado_model');
    } 

    /*
     * Listing of empleado
     */
    function index()
    {
        $data['empleado'] = $this->Empleado_model->get_all_empleado();
        
        $data['_view'] = 'empleado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new empleado
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idCargo' => $this->input->post('idCargo'),
				'nombreEmpleado' => $this->input->post('nombreEmpleado'),
            );
            
            $empleado_id = $this->Empleado_model->add_empleado($params);
            redirect('empleado/index');
        }
        else
        {
			$this->load->model('Cargo_model');
			$data['all_cargo'] = $this->Cargo_model->get_all_cargo();
            
            $data['_view'] = 'empleado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a empleado
     */
    function edit($idEmpleado)
    {   
        // check if the empleado exists before trying to edit it
        $data['empleado'] = $this->Empleado_model->get_empleado($idEmpleado);
        
        if(isset($data['empleado']['idEmpleado']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idCargo' => $this->input->post('idCargo'),
					'nombreEmpleado' => $this->input->post('nombreEmpleado'),
                );

                $this->Empleado_model->update_empleado($idEmpleado,$params);            
                redirect('empleado/index');
            }
            else
            {
				$this->load->model('Cargo_model');
				$data['all_cargo'] = $this->Cargo_model->get_all_cargo();

                $data['_view'] = 'empleado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The empleado you are trying to edit does not exist.');
    } 

    /*
     * Deleting empleado
     */
    function remove($idEmpleado)
    {
        $empleado = $this->Empleado_model->get_empleado($idEmpleado);

        // check if the empleado exists before trying to delete it
        if(isset($empleado['idEmpleado']))
        {
            $this->Empleado_model->delete_empleado($idEmpleado);
            redirect('empleado/index');
        }
        else
            show_error('The empleado you are trying to delete does not exist.');
    }
    
}
