<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empleado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get empleado by idEmpleado
     */
    function get_empleado($idEmpleado)
    {
        return $this->db->get_where('empleado',array('idEmpleado'=>$idEmpleado))->row_array();
    }
        
    /*
     * Get all empleado
     */
   function get_all_empleado()
    {
        $this->db->select('*');
        $this->db->from('empleado');
       $this->db->join('cargo','cargo.idCargo = empleado.idCargo');
     
$query = $this->db->get();
    return $query->result_array();
    }
        
    /*
     * function to add new empleado
     */
    function add_empleado($params)
    {
        $this->db->insert('empleado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update empleado
     */
    function update_empleado($idEmpleado,$params)
    {
        $this->db->where('idEmpleado',$idEmpleado);
        return $this->db->update('empleado',$params);
    }
    
    /*
     * function to delete empleado
     */
    function delete_empleado($idEmpleado)
    {
        return $this->db->delete('empleado',array('idEmpleado'=>$idEmpleado));
    }
}
